### ISSUE TITLE
NullPointerException in ForecastFragment

### ISSUE THREAD

**Issue by petrnohejl** [bartonmartin/Weather#2]
```
01-14 14:17:06.115: E/AndroidRuntime(7299): FATAL EXCEPTION: main
01-14 14:17:06.115: E/AndroidRuntime(7299): Process: cz.martinbarton.weather.android, PID: 7299
01-14 14:17:06.115: E/AndroidRuntime(7299): java.lang.NullPointerException: Attempt to invoke virtual method 'cz.martinbarton.weather.android.entity.ForecastEntity cz.martinbarton.weather.android.entity.WeatherEntity.getForecast()' on a null object reference
01-14 14:17:06.115: E/AndroidRuntime(7299):     at cz.martinbarton.weather.android.fragment.ForecastFragment$2.run(ForecastFragment.java:238)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at android.app.Activity.runOnUiThread(Activity.java:5247)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at cz.martinbarton.weather.android.task.TaskFragment.runNow(TaskFragment.java:79)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at cz.martinbarton.weather.android.task.TaskFragment.runTaskCallback(TaskFragment.java:57)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at cz.martinbarton.weather.android.fragment.ForecastFragment.onAPICallRespond(ForecastFragment.java:219)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at cz.martinbarton.weather.android.client.APICallTask.onPostExecute(APICallTask.java:101)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at cz.martinbarton.weather.android.client.APICallTask.onPostExecute(APICallTask.java:13)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at android.os.AsyncTask.finish(AsyncTask.java:632)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at android.os.AsyncTask.access$600(AsyncTask.java:177)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at android.os.Handler.dispatchMessage(Handler.java:102)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at android.os.Looper.loop(Looper.java:135)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at android.app.ActivityThread.main(ActivityThread.java:5221)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at java.lang.reflect.Method.invoke(Native Method)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at java.lang.reflect.Method.invoke(Method.java:372)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-14 14:17:06.115: E/AndroidRuntime(7299):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by bartonmartin** [comment]
Za jakých podmínek dochází k NullPointerException ? Nepodařilo se mi chování simulovat.
